from rs.calculator.cards import CardId
from rs.calculator.synergies.synergy_tags import *

SynergyBeneficiaries = {
    CardId.ANGER: [SynergyTag.STRENGTH],
    CardId.APOTHEOSIS: [],
    CardId.APPARITION: [],
    CardId.BANDAGE_UP: [],
    CardId.BASH: [SynergyTag.STRENGTH],
    CardId.BATTLE_TRANCE: [],
    CardId.BLOODLETTING: [],
    CardId.BLOOD_FOR_BLOOD: [SynergyTag.STRENGTH],
    CardId.BLUDGEON: [SynergyTag.STRENGTH],
    CardId.BODY_SLAM: [SynergyTag.STRENGTH, SynergyTag.DEXTERITY],
    CardId.BURN: [],
    CardId.CARNAGE: [SynergyTag.STRENGTH],
    CardId.CLASH: [SynergyTag.STRENGTH],
    CardId.CLEAVE: [SynergyTag.STRENGTH],
    CardId.CLOTHESLINE: [SynergyTag.STRENGTH],
    CardId.DARK_SHACKLES: [],
    CardId.DAZED: [],
    CardId.DISARM: [],
    CardId.DROPKICK: [SynergyTag.STRENGTH],
    CardId.DEFEND_R: [SynergyTag.DEXTERITY],
    CardId.DEFEND_G: [SynergyTag.DEXTERITY],
    CardId.ENTRENCH: [SynergyTag.DEXTERITY, SynergyTag.DEXTERITY],
    CardId.FEED: [SynergyTag.STRENGTH],
    CardId.FIEND_FIRE: [SynergyTag.STRENGTH, SynergyTag.STRENGTH, SynergyTag.STRENGTH],
    CardId.FLAME_BARRIER: [SynergyTag.DEXTERITY],
    CardId.FLASH_OF_STEEL: [SynergyTag.STRENGTH],
    CardId.FLEX: [],
    CardId.GHOSTLY_ARMOR: [SynergyTag.DEXTERITY],
    CardId.HAND_OF_GREED: [SynergyTag.STRENGTH],
    CardId.HEAVY_BLADE: [SynergyTag.STRENGTH, SynergyTag.STRENGTH, SynergyTag.STRENGTH],
    CardId.HEMOKINESIS: [SynergyTag.STRENGTH],
    CardId.IMMOLATE: [SynergyTag.STRENGTH],
    CardId.IMPERVIOUS: [SynergyTag.DEXTERITY],
    CardId.INFLAME: [],
    CardId.INTIMIDATE: [],
    CardId.IRON_WAVE: [SynergyTag.STRENGTH],
    CardId.JAX: [],
    CardId.LIMIT_BREAK: [SynergyTag.STRENGTH, SynergyTag.STRENGTH],
    CardId.MASTER_OF_STRATEGY: [],
    CardId.METALLICIZE: [],
    CardId.NEUTRALIZE: [SynergyTag.STRENGTH],
    CardId.OFFERING: [],
    CardId.PAIN: [],
    CardId.PERFECTED_STRIKE: [SynergyTag.STRENGTH],
    CardId.POMMEL_STRIKE: [SynergyTag.STRENGTH],
    CardId.POWER_THROUGH: [SynergyTag.DEXTERITY],
    CardId.PUMMEL: [SynergyTag.STRENGTH, SynergyTag.STRENGTH, SynergyTag.STRENGTH, SynergyTag.STRENGTH],
    CardId.RAGE: [],
    CardId.RAMPAGE: [SynergyTag.STRENGTH],
    CardId.REAPER: [SynergyTag.STRENGTH, SynergyTag.STRENGTH, SynergyTag.STRENGTH],
    CardId.REGRET: [],
    CardId.RECKLESS_CHARGE: [SynergyTag.STRENGTH],
    CardId.SEEING_RED: [],
    CardId.SHOCKWAVE: [],
    CardId.SHRUG_IT_OFF: [SynergyTag.DEXTERITY],
    CardId.SLIMED: [],
    CardId.SPOT_WEAKNESS: [],
    CardId.STRIKE_R: [SynergyTag.STRENGTH],
    CardId.SWIFT_STRIKE: [SynergyTag.STRENGTH],
    CardId.THUNDERCLAP: [SynergyTag.STRENGTH, SynergyTag.STRENGTH],
    CardId.TRIP: [],
    CardId.TWIN_STRIKE: [SynergyTag.STRENGTH],
    CardId.UPPERCUT: [SynergyTag.STRENGTH],
    CardId.WILD_STRIKE: [SynergyTag.STRENGTH],
    CardId.WOUND: []
}
