from rs.common.handlers.common_upgrade_handler import CommonUpgradeHandler


class UpgradeHandler(CommonUpgradeHandler):

    def __init__(self):
        super().__init__(priorities=[
            'apotheosis',
            'vigilance',
            'blasphemy',
            'eruption',
            'crescendo',
            'tranquility',
            'alpha',
            'lesson learned',
            'carve reality',
            'wallop',
            'windmill strike',
            'perseverance',
            'wheel kick',
            'swivel',
            'reach heaven',
            'signature move',
            'spirit shield',
            'talk to the hand',
            'master reality',
            'sands of time',
            'evaluate',
            'crush joints',
            'sash whip',
            'follow-up',
            'flying sleeves',
            'deceive reality',
            'like water',
            'wave of the hand',
            'empty body',
            'empty fist',
            'empty mind',
            'indignation',
            'rushdown',
            'tantrum',
            'mental fortress',
            'fear no evil',
            'halt',
            'flurry of blows',
            'prostrate',
        ])
