from rs.common.handlers.common_upgrade_handler import CommonUpgradeHandler


class UpgradeHandler(CommonUpgradeHandler):

    def __init__(self):
        super().__init__(priorities=[
            'apotheosis',
            'vigilance',
            'eruption',
            'crescendo',
            'tranquility',
            'carve reality',
            'wallop',
            'windmill strike',
            'perseverance',
            'wheel kick',
            'reach heaven',
            'signature move',
            'spirit shield',
            'master reality',
            'wreath of flame',
            'evaluate',
            'crush joints',
            'sash whip',
            'follow-up',
            'flying sleeves',
            'deceive reality',
            'like water',
            'empty body',
            'empty fist',
            'empty mind',
            'indignation',
            'rushdown',
            'tantrum',
            'mental fortress',
            'fear no evil',
            'halt',
            'inner peace',
            'flurry of blows',
            'prostrate',
            'worship',
            'pray',
            'prostrate',
        ])
