DESIRED_CARDS_FOR_DECK = {
    'accuracy': 4,
    'after image': 2,
    'tools of the trade': 1,  # removed if we have snecko eye
    'terror': 2,
    'neutralize': 1,
    'adrenaline': 2,
    'storm of steel': 2,
    'die die die': 2,
    'blade dance': 4,
    'infinite blades': 2,
    'eviscerate': 1,
    'survivor': 1,
    'leg sweep': 1,
    'cloak and dagger': 3,
    'sneaky strike': 2,
    'sucker punch': 1,
    'dagger spray': 2,
    'dash': 1,
    'escape plan': 2,  # removed if we have snecko eye
    'dagger throw': 1,
    'footwork': 1,
    'prepared': 1,  # removed if we have snecko eye
    'unload': 1,
    'backstab': 1,  # removed if we have snecko eye
    'master of strategy': 1,
    'flash of steel': 1,  # removed if we have snecko eye
    'finesse': 1,  # removed if we have snecko eye
    'apparition': 1,
}

DESIRED_CARDS_FROM_POTIONS = {
    'envenom': 3,
    'a thousand cuts': 3,
    'noxious fumes': 3,
    'caltrops': 3,
    'corpse explosion': 3,
    'crippling cloud': 3,
    'apotheosis': 1,
    'panache': 3,
    'sadistic nature': 3,
    'panacea': 3,
    'bandage up': 3,
    'dramatic entrance': 3,
    'blind': 1,
    'deep breath': 1,
    'enlightenment': 1,
}

CARD_REMOVAL_PRIORITY_LIST = [
    'strike',
    'defend',
    'strike+',
    'defend+',
]

HIGH_PRIORITY_UPGRADES = [
    'Apotheosis',
    'Neutralize',
    'Accuracy',
]

DESIRED_POTIONS = [
    'fruit juice',
    'fairy in a bottle',
    'focus potion',
    'cultist potion',
    'power potion',
    'potion of capacity',
    'heart of iron',
    'duplication potion',
    'distilled chaos',
    'blessing of the forge',
    'attack potion',
    'dexterity potion',
    'ambrosia',
    'fear potion',
    'essence of steel',
    'strength potion',
    'regen potion',
    'blood potion',
    'entropic brew',
    'liquid bronze',
    'energy potion',
    'skill potion',
    'ancient potion',
    'weak potion',
    'gambler\u0027s brew',
    'poison potion',
    'colorless potion',
    'flex potion',
    'swift potion',
    'bottled miracle',
    'essence of darkness',
    'fire potion',
    'explosive potion',
    'speed potion',
    'block potion',
    'cunning potion',
    'ghost in a jar',
    'stance potion',
    'smoke bomb',
    'elixir potion',
    'liquid memories',
    'snecko oil',
    'stance potion',
]