CARD_REMOVAL_PRIORITY_LIST = [
    'defend',
    'strike',
    'defend+',
    'strike+',
]

DESIRED_CARDS_FOR_DECK: dict[str, int] = {
    'perfected strike': 5,
    'offering': 1,
    'battle trance': 2,
    'reaper': 2,
    'twin strike': 2,
    'shockwave': 2,
    'thunderclap': 2,
    'dropkick': 2,
    'pommel strike': 2,
    'shrug it off': 2,
    'impervious': 2,
    'ghostly armor': 1,
    'flame barrier': 1,
    'blind': 1,
    'apotheosis': 1,
    'handofgreed': 1,
    'master of strategy': 1,
    'flash of steel': 1,
    'trip': 1,
    'dark shackles': 1,
    'swift strike': 1,
    'dramatic entrance': 1,
    'finesse': 1,
}

HIGH_PRIORITY_UPGRADES = [
    'Apotheosis',
    'Perfected Strike',
]

DESIRED_POTIONS = [
    'fruit juice',
    'fairy in a bottle',
    'cultist potion',
    'power potion',
    'potion of capacity',
    'heart of iron',
    'duplication potion',
    'distilled chaos',
    'blessing of the forge',
    'attack potion',
    'dexterity potion',
    'ambrosia',
    'fear potion',
    'essence of steel',
    'strength potion',
    'regen potion',
    'blood potion',
    'entropic brew',
    'liquid bronze',
    'energy potion',
    'skill potion',
    'ancient potion',
    'weak potion',
    'gambler\u0027s brew',
    'poison potion',
    'colorless potion',
    'flex potion',
    'swift potion',
    'bottled miracle',
    'fire potion',
    'explosive potion',
    'speed potion',
    'block potion',
    'stance potion',
    'smoke bomb',
    'elixir potion',
    'liquid memories',
    'snecko oil',
]