from enum import Enum


class Event(Enum):
    UNKNOWN = "unknown"

    ANCIENT_WRITING = "Ancient Writing"
    AUGMENTER = "Augmenter"
    A_NOTE_FOR_YOURSELF = "A Note For Yourself"
    BIG_FISH = "Big Fish"
    BONFIRE_SPIRITS = "Bonfire Spirits"
    COUNCIL_OF_GHOSTS = "Council of Ghosts"
    CURSED_TOME = "Cursed Tome"
    DEAD_ADVENTURER = "Dead Adventurer"
    DESIGNER_IN_SPIRE = "Designer In-Spire"
    DUPLICATOR = "Duplicator"
    FACE_TRADER = "Face Trader"
    FALLING = "Falling"
    FORGOTTEN_ALTAR = "Forgotten Altar"
    GOLDEN_IDOL = "Golden Idol"
    GOLDEN_SHRINE = "Golden Shrine"
    HYPNOTIZING_MUSHROOMS = "Mushrooms"  # Adding 'hypnotizing' because that word is included on the wiki
    KNOWING_SKULL = "Knowing Skull"
    LAB = "Lab"
    LIVING_WALL = "Living Wall"
    MASKED_BANDITS = "Masked Bandits"
    MATCH_AND_KEEP = "Match and Keep"
    MIND_BLOOM = "Mind Bloom"
    MYSTERIOUS_SPHERE = "Mysterious Sphere"
    NLOTH = "N'loth"
    OLD_BEGGAR = "Old Beggar"
    OMINOUS_FORGE = "Ominous Forge"
    PLEADING_VAGRANT = "Pleading Vagrant"
    PURIFIER = "Purifier"
    SCRAP_OOZE = "Scrap Ooze"
    SECRET_PORTAL = "Secret Portal"
    SENSORY_STONE = "Sensory Stone"
    SHINING_LIGHT = "Shining Light"
    THE_CLERIC = "The Cleric"
    THE_COLOSSEUM = "The Colosseum"
    THE_DIVINE_FOUNTAIN = "The Divine Fountain"
    THE_JOUST = "The Joust"
    THE_LIBRARY = "The Library"
    THE_MAUSOLEUM = "The Mausoleum"
    THE_MOAI_HEAD = "The Moai Head"
    THE_NEST = "The Nest"
    THE_SSSSSERPENT = "The Ssssserpent"
    THE_WOMAN_IN_BLUE = "The Woman in Blue"
    TOMB_OF_LORD_RED_MASK = "Tomb of Lord Red Mask"
    TRANSMOGRIFIER = "Transmogrifier"
    UPGRADE_SHRINE = "Upgrade Shrine"
    VAMPIRES = "Vampires(?)"
    WE_MEET_AGAIN = "We Meet Again!"
    WHEEL_OF_CHANGE = "Wheel of Change"
    WINDING_HALLS = "Winding Halls"
    WING_STATUE = "Wing Statue"
    WORLD_OF_GOOP = "World of Goop"

