from rs.ai.requested_scaling.synergies.synergy_tags import SynergyTag
from rs.calculator.cards import CardId

SynergyBeneficiaries = {
    CardId.ANGER: [],
    CardId.APOTHEOSIS: [],
    CardId.APPARITION: [],
    CardId.BANDAGE_UP: [SynergyTag.EXHAUST],
    CardId.BASH: [],
    CardId.BATTLE_TRANCE: [],
    CardId.BLOODLETTING: [],
    CardId.BLOOD_FOR_BLOOD: [],
    CardId.BLUDGEON: [],
    CardId.BODY_SLAM: [],
    CardId.BURN: [SynergyTag.STATUS],
    CardId.CARNAGE: [],
    CardId.CLASH: [],
    CardId.CLEAVE: [SynergyTag.STRENGTH],
    CardId.CLOTHESLINE: [],
    CardId.DARK_SHACKLES: [SynergyTag.EXHAUST],
    CardId.DAZED: [SynergyTag.EXHAUST, SynergyTag.STATUS],
    CardId.DISARM: [SynergyTag.EXHAUST],
    CardId.DROPKICK: [],
    CardId.DEFEND_R: [],
    CardId.DEFEND_G: [],
    CardId.ENTRENCH: [],
    CardId.FEED: [SynergyTag.EXHAUST],
    CardId.FIEND_FIRE: [SynergyTag.EXHAUST, SynergyTag.STRENGTH],
    CardId.FLAME_BARRIER: [],
    CardId.FLASH_OF_STEEL: [],
    CardId.FLEX: [],
    CardId.GHOSTLY_ARMOR: [SynergyTag.EXHAUST],
    CardId.HAND_OF_GREED: [],
    CardId.HEAVY_BLADE: [SynergyTag.STRENGTH, SynergyTag.STRENGTH],
    CardId.HEMOKINESIS: [],
    CardId.IMMOLATE: [],
    CardId.IMPERVIOUS: [SynergyTag.EXHAUST],
    CardId.INFLAME: [SynergyTag.STRENGTH],
    CardId.INTIMIDATE: [SynergyTag.EXHAUST],
    CardId.IRON_WAVE: [],
    CardId.JAX: [SynergyTag.STRENGTH],
    CardId.LIMIT_BREAK: [SynergyTag.STRENGTH],
    CardId.MASTER_OF_STRATEGY: [SynergyTag.EXHAUST],
    CardId.METALLICIZE: [],
    CardId.NEUTRALIZE: [],
    CardId.OFFERING: [SynergyTag.EXHAUST],
    CardId.PAIN: [],
    CardId.PERFECTED_STRIKE: [],
    CardId.POMMEL_STRIKE: [],
    CardId.POWER_THROUGH: [SynergyTag.STATUS],
    CardId.PUMMEL: [SynergyTag.STRENGTH],
    CardId.RAGE: [],
    CardId.RAMPAGE: [],
    CardId.REAPER: [SynergyTag.STRENGTH],
    CardId.REGRET: [],
    CardId.RECKLESS_CHARGE: [],
    CardId.SEEING_RED: [SynergyTag.EXHAUST],
    CardId.SHOCKWAVE: [SynergyTag.EXHAUST],
    CardId.SHRUG_IT_OFF: [],
    CardId.SLIMED: [SynergyTag.STATUS],
    CardId.SPOT_WEAKNESS: [SynergyTag.STRENGTH],
    CardId.STRIKE_R: [],
    CardId.SWIFT_STRIKE: [],
    CardId.THUNDERCLAP: [],
    CardId.TRIP: [],
    CardId.TWIN_STRIKE: [SynergyTag.STRENGTH],
    CardId.UPPERCUT: [],
    CardId.WILD_STRIKE: [],
    CardId.WOUND: [],
    CardId.FEEL_NO_PAIN: [SynergyTag.EXHAUST],
    CardId.DARK_EMBRACE: [],
    CardId.BLADE_DANCE: [],
    CardId.EVOLVE: [],
    CardId.FIRE_BREATHING: [],
    CardId.BURNING_PACT: [SynergyTag.EXHAUST, SynergyTag.STATUS]
}


def synergyBeneficiariesCardIdStrings():
    return [v.value for v in SynergyBeneficiaries.keys()]
