DESIRED_CARDS_FOR_DECK = {
    'blasphemy': 1,
    'talk to the hand': 3,
    'rushdown': 1,
    'tantrum': 2,
    'battle hymn': 1,
    'mental fortress': 2,
    'vigilance': 1,
    'tranquility': 2,
    'wallop': 1,
    'flurry of blows': 2,
    'empty body': 2,
    'indignation': 1,
    'crush joints': 1,
    'fear no evil': 2,
    'empty fist': 1,
    'reach heaven': 1,
    'inner peace': 1,
    'cut through fate': 1,
    'eruption': 1,
    'crescendo': 1,
    'halt': 1,
    'ritual dagger': 1,
    'deceive reality': 1,
    'carve reality': 1,
    'spirit shield': 1,
    'sands of time': 1,
    'ragnarok': 1,
    'perseverance': 2,
    'wheel kick': 1,
    'like water': 1,
}  # some get removed if snecko eye or runic pyramid is present

DESIRED_CARDS_FROM_POTIONS = {
    'apotheosis': 1,
    'mental fortress': 5,
    'master of strategy': 3,
    'wish': 2,
    'deva form': 2,
    'like water': 3,
    'devotion': 2,
    'rushdown': 3,
    'master reality': 1,
    'establishment': 2,
    'talk to the hand': 7,
    'scrawl': 1,
    'lesson learned': 1,
    'dark shackles': 2,
    'panache': 3,
    'panacea': 3,
    'deus ex machina': 1,
    'bandage up': 3,
    'dramatic entrance': 3,
    'trip': 1,
    'blind': 1,
    'enlightenment': 2,
    'hand of greed': 2,
    'sadistic nature': 2,
}

CARD_REMOVAL_PRIORITY_LIST = [
    'conjureblade',
    'conjureblade+',
    'vault',
    'vault+',
    'omniscience',
    'omniscience+',
    'meditate',
    'meditate+',
    'defend',
    'strike',
    'Wish',
    'Wish+',
    'defend+',
    'strike+',
    'bite']

HIGH_PRIORITY_UPGRADES = [
    'Apotheosis',
    'Blasphemy',
    'Eruption',
]
